CREATE TABLE JOB
(
ID INTEGER,
MAILSERVER VARCHAR(20),
USERNAME VARCHAR(20),
PASSWORD VARCHAR(20),
PORT VARCHAR(20),
CURRENT_STATUS VARCHAR(20),
PROCESSID VARCHAR(20),
MONITOR VARCHAR(20),
PRIMARY KEY (ID)
);

INSERT INTO JOB VALUES (1,'mail.abc.com','user','abcd', '993', null , null ,'Y' );
INSERT INTO JOB VALUES (2,'smtp.gmail.com','user','abcd', '993', null , null ,'Y' );

